export const siteConfig = {
  brand: 'Tamgur',
  links: {
    models: '/pricing',
    pricing: '/pricing',
    docs: 'https://doc.tamgur.tech/',
    openClawDocs: 'https://doc.tamgur.tech/toolTips',
    apiDocs: 'https://api.tamgur.tech/docs/api',
    codexDocs: 'https://api.tamgur.tech/docs/codex',
    status: '/status',
    console: 'https://api.tamgur.tech/dashboard/models',
    login: '/login',
    recharge: 'https://api.tamgur.tech/wallet',
    imageGeneration: '/playground',
    telegramGroup: 'https://t.me/chloe_yan_cyu',
    telegram: 'https://t.me/chloe_yan_cyu',
    support: 'mailto:tamgurcyu@gmail.com?subject=Tamgur%20Support',
    contact: 'mailto:tamgurcyu@gmail.com?subject=Tamgur%20Contact',
    wechatGroup: '/wechat-group',
  },
} as const;
